### ISSUE TITLE
Error: MET and METPLUS installation failed.

### ISSUE THREAD

**Issue by ginpain** [HathewayWill/WRF-MOSIT#31]
**Describe the bug**

I attempted to install the Weather Research & Forecasting Model (WRF) using WRF-MOSIT on Ubuntu 22.04.4 (Windows Sub-Linux Ubuntu) and encountered an error during the MET and METPLUS installation. Here is a screenshot of the error and the logfile:

![met-error](https://github.com/HathewayWill/WRF-MOSIT/assets/112572193/3807a7b8-39f5-4009-b72d-084678c89b4e)
[logscopy.txt](https://github.com/HathewayWill/WRF-MOSIT/files/14492923/logscopy.txt)

**Additional context**
The error indicates that I am using Python 3.9.18, but when I checked the Python version, it showed Python 3.10.4.
![pythonversion](https://github.com/HathewayWill/WRF-MOSIT/assets/112572193/0df3560e-d52c-43d4-8c59-f3ff13f65826)

**Comment by HathewayWill** [comment]
@ginpain 

It's the intel compilers, they are an issue with WRF on subsystem linux.  Please use GNU for now

**Comment by ginpain** [comment]
Alright, thank you so much
