### ISSUE TITLE
./geogrid.exe: error while loading shared libraries: libnetcdf.so.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ginpain** [HathewayWill/WRF-MOSIT#32]
**Describe the bug**
i have successfully installed wrf using wrf-mosit on ubuntu 22.04 on wsl.
After setting my domain etc in the namelist.wps file, when I run the geogrid program, I get this error:
./geogrid.exe: error while loading shared libraries: libnetcdf.so.7: cannot open shared object file: No such file or directory

**Comment by HathewayWill** [comment]
Are you using GNU or Intel compilers @ginpain ?

**Comment by HathewayWill** [comment]
> I'm using the GNU compiler

Did you export the libraries prior to running geogrid?

`#!/bin/bash

#setting environment for WRF model to run
export LD_LIBRARY_PATH=/home/workhorse/WRF/Libs/NETCDF/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/home/workhorse/WRF/Libs/grib2/lib:$LD_LIBRARY_PATH
export PATH=/home/workhorse/WRF/Libs/MPICH/bin:$PATH
export PATH=/home/workhorse/WRF/Libs/grib2/lib:$PATH
`

**Comment by ginpain** [comment]
No, i did not export the libraries, are these the only ones i need to export?

**Comment by HathewayWill** [comment]
> No, i did not export the libraries, are these the only ones i need to export?

Should be.

Just change the pathing names to match your system.

**Comment by ginpain** [comment]
i did it, and changed the path to my user, but the geogrid still gives the same error

**Comment by HathewayWill** [comment]
do you have another version of WRF on this user account or modified the bashrc file?

**Comment by ginpain** [comment]
No i don't  have another versions of wrf and i did not modify the bashrc file

**Comment by HathewayWill** [comment]
okay, hmm try checking the netcdf file folder for that file that it says it can't find.  If it exists then we have a different issue than if it doesn't.

**Comment by ginpain** [comment]
it does exist 
![image (3)](https://github.com/HathewayWill/WRF-MOSIT/assets/112572193/660c6c59-668c-482e-8011-1b38d47e15ec)

**Comment by ginpain** [comment]
positive update about the error : the geogrid.exe works successfully only when i export the libs but if i open a new terminal session i have export the libs again

**Comment by HathewayWill** [comment]
ah so that's what it was

**Comment by HathewayWill** [comment]
So you were sucessful @ginpain

**Comment by ginpain** [comment]
I apologize for the delayed response, Mr. @HathewayWill  The issue has been resolved. Now, I'm wondering if it would be appropriate to include the export lines in the bashrc file to ensure they are permanent.

**Comment by ginpain** [comment]
Thank you so much for your assistance! I truly appreciate your help and commend your efforts in creating such an incredible script WRF-MOSIT. It has certainly made the installation process much more manageable for me as a beginner. I eagerly await any updates you make to the readme file. Thanks again!

**Comment by HathewayWill** [comment]
You are very welcome.  I'm going to close this issue now since we resolved it.
