### ISSUE TITLE
wrf-solar

### ISSUE THREAD

**Issue by fipoucat** [HathewayWill/WRF-MOSIT#33]
could you please add wrf-solar?

**Comment by HathewayWill** [comment]
Good afternoon,

WRF Solar is actually now integrated into WRF ARW as of version 4.2. 

So if you install WRF ARW you will have it. 

The installation is the same as ARW which is why I didn't make a separate one for it

**Comment by fipoucat** [comment]
I have WRF ARW version 5 and 5.1, which exe file to use or it is in the namelist.input settings?

Thanks also for the nice talk you did today.

**Comment by HathewayWill** [comment]
I haven't used it myself personally. 

But in the forum there's a specific section for solar. 

https://forum.mmm.ucar.edu/forums/wrf-solar.112/

Their official website has some tutorials too

https://ral.ucar.edu/solutions/products/wrf-solar

**Comment by fipoucat** [comment]
Thank you
