### ISSUE TITLE
Issue using Intel compiler

### ISSUE THREAD

**Issue by andrewsfisk** [HathewayWill/WRF-MOSIT#35]
Hi,

First, thank you so much for providing this resource. I have WRF running on an AWS instance thanks to your script. Unfortunatley I recently accidently deleted obsgrid.exe while trying to remove old obs so have been trying to recompile a version (intel) on Ubuntu to copy it across. While doing that I have encountered the following error. I'm using the Ubuntu release you mention it has been tested on in the docs on an AWS EC2 instance. I have tried running both GNU and Intel options in your scrip options but no success. I just wanted to let you know this has occured. 

Thanks again for your effort in providing this.

Cheers,
Andrew

Enviroment Test 1 Passed
I am going to wait for 3 seconds only ...
Test 2
ifort: remark #10448: Intel(R) Fortran Compiler Classic (ifort) is now deprecated and will be discontinued late 2024. Intel recommends that customers transition now to using the LLVM-based Intel(R) Fortran Compiler (ifx) for continued Windows* and Linux* support, new language support, new language features, and optimizations. Use '-diag-disable=10448' to disable this message.
 Assume Fortran 2003: has FLUSH, ALLOCATABLE derived type, and ISO C Binding
 SUCCESS test 2 fortran only free format
Enviroment Test 2 Passed

I am going to wait for 3 seconds only ...
Test 3
./WRF-MOSIT.sh: line 24016: icc: command not found
 Assume Fortran 2003: has FLUSH, ALLOCATABLE derived type, and ISO C Binding
 SUCCESS test 2 fortran only free format
Enviroment Test 3 Passed

I am going to wait for 3 seconds only ...
Test 4
./WRF-MOSIT.sh: line 24030: icc: command not found
ifort: remark #10448: Intel(R) Fortran Compiler Classic (ifort) is now deprecated and will be discontinued late 2024. Intel recommends that customers transition now to using the LLVM-based Intel(R) Fortran Compiler (ifx) for continued Windows* and Linux* support, new language support, new language features, and optimizations. Use '-diag-disable=10448' to disable this message.
ifort: remark #10448: Intel(R) Fortran Compiler Classic (ifort) is now deprecated and will be discontinued late 2024. Intel recommends that customers transition now to using the LLVM-based Intel(R) Fortran Compiler (ifx) for continued Windows* and Linux* support, new language support, new language features, and optimizations. Use '-diag-disable=10448' to disable this message.
ifort: error #10236: File not found:  'TEST_4_fortran+c_c.o'
 Assume Fortran 2003: has FLUSH, ALLOCATABLE derived type, and ISO C Binding
 SUCCESS test 2 fortran only free format
Enviroment Test 4 Passed

I am going to wait for 3 seconds only ...
cp: cannot stat '/home/ubuntu/WRF_Intel/Libs/NETCDF/include/netcdf.inc': No such file or directory

Library Compatibility Tests
Test 1
ifort: remark #10448: Intel(R) Fortran Compiler Classic (ifort) is now deprecated and will be discontinued late 2024. Intel recommends that customers transition now to using the LLVM-based Intel(R) Fortran Compiler (ifx) for continued Windows* and Linux* support, new language support, new language features, and optimizations. Use '-diag-disable=10448' to disable this message.
01_fortran+c+netcdf_f.f(5): error #5102: Cannot open include file 'netcdf.inc'
        INCLUDE 'netcdf.inc'
----------------^
compilation aborted for 01_fortran+c+netcdf_f.f (code 1)
./WRF-MOSIT.sh: line 24056: icc: command not found
ifort: remark #10448: Intel(R) Fortran Compiler Classic (ifort) is now deprecated and will be discontinued late 2024. Intel recommends that customers transition now to using the LLVM-based Intel(R) Fortran Compiler (ifx) for continued Windows* and Linux* support, new language support, new language features, and optimizations. Use '-diag-disable=10448' to disable this message.
ifort: error #10236: File not found:  '01_fortran+c+netcdf_f.o'
ifort: error #10236: File not found:  '01_fortran+c+netcdf_c.o'
./WRF-MOSIT.sh: line 24060: ./a.out: No such file or directory
Compatibility Compiler Test 1 Failed

**Comment by HathewayWill** [comment]
@andrewsfisk 

Good afternoon Andrew,

First of all I'm glad to hear that it works on AWS for you.

The first question is when did you install the WRF on AWS server?  Was it in 2022 or 2023?

**Comment by andrewsfisk** [comment]
I believe around mid 2023. I used the Intel option then. I’ve set up a new AWS instance and tried a mid 2023 Ubuntu install as well as the current version. Same issue for both. Thank you for your reply.On 6 Jun 2024, at 09:50, HathewayWill ***@***.***> wrote:﻿
@andrewsfisk
Good afternoon Andrew,
First of all I'm glad to hear that it works on AWS for you.
The first question is when did you install the WRF on AWS server?  Was it in 2022 or 2023?

**Comment by HathewayWill** [comment]
@andrewsfisk 

Good evening,

So in mid 2023 the intel compilers changed and broke the code.  So if you used the wrf-mosit script it downloads the new compilers and tries to install it with the old method.  Which is why these errors occur.
I am currently working on them to get updated I'm just waiting for WPS 4.6.0 to be released so that I don't have users downloading on version for WRF 4.6.0 and then again for WPS 4.6.0

As for the GNU it should work without a problem on ubuntu 22 on AWS.  Which version of ubuntu are you using for GNU?

**Comment by andrewsfisk** [comment]
Ahh I see that makes sense. I tried GNU on a latest Ubuntu install I believe. I’ve terminated the AWS instance now sorry. I should have sent you the error. I’m really only interested in getting the Intel compiled ‘obsgrid.exe’ program out of WPS to replace my accidentally deleted copy but if the compiler is different it probably won’t work anyway. Sounds like I should probably just re install the entire set up. On 6 Jun 2024, at 10:10, HathewayWill ***@***.***> wrote:﻿
@andrewsfisk
Good evening,
So in mid 2023 the intel compilers changed and broke the code.  So if you used the wrf-mosit script it downloads the new compilers and tries to install it with the old method.  Which is why these errors occur.
I am currently working on them to get updated I'm just waiting for WPS 4.6.0 to be released so that I don't have users downloading on version for WRF 4.6.0 and then again for WPS 4.6.0
As for the GNU it should work without a problem on ubuntu 22 on AWS.  Which version of ubuntu are you using for GNU?

**Comment by HathewayWill** [comment]
@andrewsfisk 

It can be done but it will require a webcall to do it.  Basically you will be building from scratch again and need to do certain steps.  I actually would find it helpful to figure it out

**Comment by andrewsfisk** [comment]
I’d certainly appreciate that if you were prepared to take the time to help. Otherwise I can wait until you’ve updated the script and use that for a fresh install instead…Thank youOn 6 Jun 2024, at 10:33, HathewayWill ***@***.***> wrote:﻿
@andrewsfisk
It can be done but it will require a webcall to do it.  Basically you will be building from scratch again and need to do certain steps.  I actually would find it helpful to figure it out

**Comment by HathewayWill** [comment]
Whichever you would prefer.  I have plenty of time to spare.

**Comment by andrewsfisk** [comment]
Ok fantastic I will take you up on your offer of a web call. On 6 Jun 2024, at 11:20, HathewayWill ***@***.***> wrote:﻿
Whichever you would prefer.  I have plenty of time to spare.

**Comment by HathewayWill** [comment]
@andrewsfisk 

Which timezone are you in?

**Comment by andrewsfisk** [comment]
I’m in Melbourne, Australia which is UTC -10 hoursOn 7 Jun 2024, at 00:54, HathewayWill ***@***.***> wrote:﻿
@andrewsfisk
Which timezone are you in?

**Comment by andrewsfisk** [comment]
I’m busy over the weekend but have all day/evening Monday freeOn 7 Jun 2024, at 00:54, HathewayWill ***@***.***> wrote:﻿
@andrewsfisk
Which timezone are you in?

**Comment by HathewayWill** [comment]
@andrewsfisk 

Which timezone are you in?

So 15hr difference. UTC -5 here in the states

**Comment by andrewsfisk** [comment]
Sorry we are UTC +10. So yes you are 15 hours behind Melbourne if my maths is correct!

**Comment by HathewayWill** [comment]
@andrewsfisk 

If you haven't already add me on linkedin and we can discuss there directly a time to meet for a webcall. 
https://www.linkedin.com/in/williamhatheway/


 I try to limit the number of places my email is public

**Comment by andrewsfisk** [comment]
No probs. I don’t have LinkedIn but I can sign up if required. Could we chat via WhatsApp or similar? I’m happy to add my email to the chat and you can use privately if thats better? I’m easy whatever works. If you prefer LinkedIn I'll do that

**Comment by HathewayWill** [comment]
@andrewsfisk 

you can put your email here then ill delete it once i have it

**Comment by andrewsfisk** [comment]
Done. ***@***.***

**Comment by HathewayWill** [comment]
@andrewsfisk oh look at that github blocks personal emails.  Well that's annoying.

**Comment by andrewsfisk** [comment]
No way! Ok should I ty giving you my phone number and you can add me to WhatsApp?

+61419232239

**Comment by HathewayWill** [comment]
going to mark this resolved as we are direct messaging
