### ISSUE TITLE
 WRF-MOSIT can't connect to www2.mmm.ucar.edu to retrieve tests.

### ISSUE THREAD

**Issue by ginpain** [HathewayWill/WRF-MOSIT#37]
Hello, I was trying to install WRF on a machine with Ubuntu 22 using WRF-MOSIT. The script was running smoothly until I encountered this error:
`
--2024-07-15 12:46:33--  https://www2.mmm.ucar.edu/wrf/OnLineTutorial/compile_tutorial/tar_files/Fortran_C_NETCDF_MPI_tests.tar
Resolving www2.mmm.ucar.edu (www2.mmm.ucar.edu)... 128.117.13.91
Connecting to www2.mmm.ucar.edu (www2.mmm.ucar.edu)|128.117.13.91|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-07-15 12:46:34 ERROR 403: Forbidden.

--2024-07-15 12:46:34--  https://www2.mmm.ucar.edu/wrf/OnLineTutorial/compile_tutorial/tar_files/Fortran_C_tests.tar
Resolving www2.mmm.ucar.edu (www2.mmm.ucar.edu)... 128.117.13.91
Connecting to www2.mmm.ucar.edu (www2.mmm.ucar.edu)|128.117.13.91|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-07-15 12:46:35 ERROR 403: Forbidden.

tar: Fortran_C_tests.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: Fortran_C_NETCDF_MPI_tests.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
 
 
 
Environment Testing 
Test 1
f951: Error: Cannot open file ‘TEST_1_fortran_only_fixed.f’
<built-in>: Fatal Error: cannot open input file: TEST_1_fortran_only_fixed.f
compilation terminated.
./WRF-MOSIT.sh: line 23557: ./a.out: No such file or directory
Environment Compiler Test 1 Failed

`

It seems that the www2.mmm.ucar.edu website is experiencing accessibility issues.
![image](https://github.com/user-attachments/assets/0bb0d698-0bfa-4e6d-a182-c3b0cef6f493)

**Comment by HathewayWill** [comment]
NCAR had internet issues this issue is resolved
