### ISSUE TITLE
Duplicate "then"

### ISSUE THREAD

**Issue by am-thyst** [HathewayWill/WRF-MOSIT#38]
There are several instances in WRF_MOSIT.sh that have syntax errors relating to a duplicate "then" in the if loops.

For example, L2035:
```bash
    if [ $TEST_PASS -ge 1 ] then
        then
```

As a fix, I would suggest typing the following commands into vim:
```bash
:%s!] then!] !g
:%s!) then!) !g
```

to repair all instances.

**Comment by HathewayWill** [comment]
Fixed with latest commit

https://github.com/HathewayWill/WRF-MOSIT/commit/33d15e566a741ebe62c595dfbafdcfb552b89f8a

**Comment by HathewayWill** [comment]
@am-thyst please test and verify
