### ISSUE TITLE
Error in the compilation of the WRF-CHEM tools

### ISSUE THREAD

**Issue by ELVIS9207** [HathewayWill/WRF-MOSIT#40]
Hello Doctor, good afternoon.

I would like to inform you that I used WRF-MOSIT to install WRF-Chem. During the compilation of the WRF-Chem tools, specifically for FINN, I understand that the executable should have been generated, correct? Since this did not happen, I tried to do it manually, but I encountered an error. I would greatly appreciate your guidance on how to resolve this issue. Thank you in advance.

My PC specifications:

Distributor: Linux Mint
Description: Linux Mint 22
Release: 22
Codename: Wilma
Disk space:

mpfs: 6.3G 2.9M 6.3G 1% /run
efivarfs: 246K 160K 82K 67% /sys/firmware/efi/efivars
/dev/sda2: 1.8T 441G 1.3T 26% /
tmpfs (dev/shm): 32G 430M 31G 2% /dev/shm
tmpfs (run/lock): 5.0M 20K 5.0M 1% /run/lock
/dev/nvme0n1p1: 256M 98M 159M 39% /boot/efi
tmpfs (run/user/1000): 6.3G 264K 6.3G 1% /run/user/1000

![Captura de pantalla de 2024-10-22 17-55-13](https://github.com/user-attachments/assets/9c9c9471-57f4-471e-a77a-f5cf9e9fd5af)

**Comment by HathewayWill** [comment]
######################## Fire INventory from NCAR (FINN) ###########################
	# Fire INventory from NCAR (FINN): A daily fire emissions product for atmospheric chemistry models
	# https://www2.acom.ucar.edu/modeling/finn-fire-inventory-ncar
	echo " "
	echo "###########################################"
	echo " Please see folder for details about FINN."
	echo "###########################################"
	echo " "

**Comment by HathewayWill** [comment]
to compile FINN you'll need to export the library file locations and use the the fallow argument mismatch

	export PNETCDF=$DIR/grib2
	export PATH=$DIR/NETCDF/bin:$PATH
	export NETCDF=$DIR/NETCDF
	export HDF5=$DIR/grib2
	export PHDF5=$DIR/grib2
	export LD_LIBRARY_PATH=$DIR/grib2/lib:$LD_LIBRARY_PATH
	export JASPERLIB=$DIR/grib2/lib
	export JASPERINC=$DIR/grib2/include
	export PATH=$DIR/MPICH/bin:$PATH
	export MPIFC=$DIR/MPICH/bin/mpifort
	export MPIF77=$DIR/MPICH/bin/mpifort
	export MPIF90=$DIR/MPICH/bin/mpifort
	export MPICC=$DIR/MPICH/bin/mpicc
	export MPICXX=$DIR/MPICH/bin/mpicxx
        export fallow_argument=-fallow-argument-mismatch
	export boz_argument=-fallow-invalid-boz
	export FFLAGS="$fallow_argument -m64"
	export FCFLAGS="$fallow_argument -m64"
