### ISSUE TITLE
Error compiling WRFCHEM

### ISSUE THREAD

**Issue by LucasCalbucuraZ** [HathewayWill/WRF-MOSIT#42]
Hello, I have been trying to compile WRFCHEM using the GNU compiler on Ubuntu 20.04, but the following error message appears:

![Captura de pantalla de 2024-10-23 12-36-57](https://github.com/user-attachments/assets/ebc5279c-b24a-46a8-90e5-155eca695167)

[WRF-MOSIT_issues_20241023.zip](https://github.com/user-attachments/files/17494589/WRF-MOSIT_issues_20241023.zip)

I am attaching the log and the script I used in a ZIP file. I have also included a screenshot of the directories generated by the script.  

![Captura de pantalla de 2024-10-23 11-16-25](https://github.com/user-attachments/assets/2bf70734-db6a-4f87-beea-747eb4b78231)

Thank you.

**Comment by HathewayWill** [comment]
@LucasCalbucuraZ 

should fix it now


https://github.com/HathewayWill/WRF-MOSIT/commit/2ae6c51a0c1ca21987d6251a09627ccec707b673

**Comment by HathewayWill** [comment]
closing as the issues is related to ubuntu 20
