### ISSUE TITLE
 Error compiling WRFCHEM on Debian 12.7

### ISSUE THREAD

**Issue by LucasCalbucuraZ** [HathewayWill/WRF-MOSIT#43]
Hello! 

Im trying to compile WRFCHEM using the GNU compiler on Debian 12.7, but the following error message appears:

![Captura de pantalla 2024-10-28 121000](https://github.com/user-attachments/assets/a86bdaed-3af7-4a95-be5d-b48c809433b7)

[WRF-MOSIT_issues_20241028.zip](https://github.com/user-attachments/files/17544537/WRF-MOSIT_issues_20241028.zip)

I am attaching the log and the script I used in a ZIP file. I have also included a screenshot of the directories generated by the script.

![Captura de pantalla 2024-10-28 114207](https://github.com/user-attachments/assets/0a2a6c69-e49f-483f-930d-443dfec45b4c)

Thank you in advance.

**Comment by HathewayWill** [comment]
@LucasCalbucuraZ 

Where did you get the os image. I want to try to recreate it

**Comment by LucasCalbucuraZ** [comment]
@HathewayWill 

    [bookworm (stable)](https://packages.debian.org/bookworm/debian-installer-12-netboot-amd64) (misc): Debian-installer network boot images for amd64 (20230607+deb12u7)

**Comment by HathewayWill** [comment]
> @HathewayWill
> 
> bookworm (stable) (https://packages.debian.org/bookworm/debian-installer-12-netboot-amd64) (misc): Debian-installer network boot images for amd64 (20230607+deb12u7)

Honestly Debian is more unstable than ubuntu and doesn't really run much faster using WRF.  I would stick to ubuntu if possible since it is more actively developed and tested.

But I will try to get this to work later today

**Comment by HathewayWill** [comment]
@LucasCalbucuraZ 

try installing it now, fixed a few issues in the scripts.  Delete the folders that were already downloaded and reclone them down again

**Comment by LucasCalbucuraZ** [comment]
@HathewayWill 

I'll try it. Thank you so much!

I keep you updated.

**Comment by LucasCalbucuraZ** [comment]
@HathewayWill 

It seems that the fix has overcome the previous error, and has managed to move forward :D. This new error apears now (zip file attached) 

![Captura de pantalla 2024-10-03 150006](https://github.com/user-attachments/assets/ff9f4462-1eb6-4de7-b97e-f3406a24fa1f)

[WRFCHEM-issues-20241109.zip](https://github.com/user-attachments/files/17686051/WRFCHEM-issues-20241109.zip)

Thank you!

**Comment by LucasCalbucuraZ** [comment]
@HathewayWill 

New one appears:

![Captura de pantalla 2024-11-09 131634](https://github.com/user-attachments/assets/86abe7f6-58b7-42e7-96db-1be124121b3f)

[WRFCHEM-issues-20241109-1318.zip](https://github.com/user-attachments/files/17688614/WRFCHEM-issues-20241109-1318.zip)

**Comment by HathewayWill** [comment]
@LucasCalbucuraZ 

did it work for you after the changes?

**Comment by LucasCalbucuraZ** [comment]
@HathewayWill 

yes! after removing nceplibs and upp portion from the script, it works :D 

thanks a lot!
