### ISSUE TITLE
HWRF

### ISSUE THREAD

**Issue by imuwn** [HathewayWill/WRF-MOSIT#45]
Hello Dr. HathewayWill,

I hope this message finds you well. I wanted to ask if you have removed the HWRF installation files or resources from your GitHub repository.

Thank you in advance for your clarification.

**Comment by HathewayWill** [comment]
Good morning,

Yes I had to remove it as I could no longer get it to work with modern compilers.  This software was discontinued about 10 years ago and I was able to trick it to work on modern compilers.  But now that option is no longer viable.
